language: node_js
node_js:
  - "10"
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
notifications:
  email: false
before_install:
  - apt-get install fakeroot
script:
  - yarn dist-packager && yarn deb
