language: node_js
node_js:
  - "10"
sudo: true
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
notifications:
  email: false
before_install:
  - sudo apt-get install fakeroot
script:
  - yarn dist
